### ISSUE TITLE
Offsets don't always apply in HS2

### ISSUE THREAD

**Issue by Animal42069** [Mantas-2155X/BetterHScenes#3]
I think there is a bit of an issue with the offsets in HS2.  They don't always apply when not using one offset for all positions.  I'm pretty sure this is due to H_Lookat_dan::SetDanInfo not getting called every time a motion changes, unlike in AIS where that function does get called.

A simple fix would be to check the current motion every frame and apply the offsets if it changes, but that sounds like a pretty expensive fix.  When I have some free time, I'll see if I can find a better hook to use

**Comment by Mantas-2155X** [comment]
Merged your PR, thanks for your work as usual :)
